name: Publish

on:
  push:
    tags:
      - "v*"

jobs:
  checks:
    permissions:
      contents: read
    uses: ./.github/workflows/ci.yml

  publish:
    needs: checks
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/actions/setup-node
      - run: pnpm publish -r --access public --no-git-checks --provenance
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
